name: testing

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  testing-by-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
    - name: Run tests
      run: |
        pytest --cov app
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: VascoSch92/uast
  tests-suite:
    runs-on: ubuntu-latest
    needs: testing-by-version
    if: success() || failure()
    steps:
    - name: Check status of testing-by-version
      run: |
        if [ "${{ needs.testing-by-version.result }}" != "success" ]; then
          echo "Previous job(s) failed."
          exit 1
        else
          echo "All previous jobs passed."
        fi
